name: "Code Format Action"
author: "@musman920"
description: "An action to run python code format tools."
branding:
  icon: "truck"
  color: "gray-dark"

inputs:
  config:
    description: "Path to the config file"
    required: true
    default: "pyproject.toml"

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - run: |
        python -m pip install --upgrade pip
        pip install black isort
      shell: bash
    - run: |
        black --config ${{ inputs.config }} --check . 
        isort --settings-file ${{ inputs.config }}  --check .
      shell: bash

