name: "Code Format Action"
author: "@musman920"
description: "An action to run python code format tools."
branding:
  icon: "truck"
  color: "gray-dark"

inputs:
  config:
    description: "Path to the config file"
    required: true
    default: "pyproject.toml"

inputs:
  python-version:
    description: 'Python version to run black & isort'
    required: false
    default: "3.11"

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.pyton-version }}
    - run: |
        python -m pip install --upgrade pip
        pip install black isort
      shell: bash
    - run: |
        black --config ${{ inputs.config }} --check . 
        isort --settings-file ${{ inputs.config }}  --check .
      shell: bash
