name: "Code Format Action"
author: "@musman920"
description: "An action to run code format tools via poetry."
branding:
  icon: "truck"
  color: "gray-dark"
runs:
  using: "composite"
  steps:
    - run: |
        python -m pip install --upgrade pip
        pip install poetry==1.2.2
        poetry add black==22.3.0 isort==5.10.1 flake8==4.0.1 bandit==1.7.0 safety==1.10.3
        poetry run black --check .
        poetry run isort --check .        
      shell: bash
