name: "Code Format Action"
author: "@musman920"
description: "An action to run code format tools via poetry."
branding:
  icon: "truck"
  color: "gray-dark"
runs:
  using: "composite"
  steps:
    - name: "Run black"
    - run: |
        python -m pip install --upgrade pip
        pip install black isort
      shell: bash
    - name: "Run isort"
    - run: |
        python black --config pyproject.toml --check . 
        python isort --settings-file pyproject.toml --check .
      shell: bash

# look for something like requires
# make config location dynamic:? root